export const TICKET_CREATE_SUCCESS = 'TICKET_CREATE_SUCCESS';
export const TICKET_CREATE_FAILURE = 'TICKET_CREATE_FAILURE';
export const TICKET_CREATE_LOADING = 'TICKET_CREATE_LOADING';
export const TICKET_EDIT_LOADING = 'TICKET_EDIT_LOADING';
export const TICKET_EDIT_FAILURE = 'TICKET_EDIT_FAILURE';
export const TICKET_EDIT_SUCCESS = 'TICKET_EDIT_SUCCESS';
export const TICKET_DELETE_REQUEST = 'TICKET_DELETE_REQUEST';
export const TICKET_DELETE_SUCCESS = 'TICKET_DELETE_SUCCESS';