export const SET_PROJECT_REQUEST = 'SET_PROJECT_REQUEST';
export const SET_PROJECT_SUCCESS = 'SET_PROJECT_SUCCESS';
export const SET_PROJECT_ERROR = 'SET_PROJECT_ERROR';
export const SET_PROJECT_EDIT_REQUEST = 'SET_PROJECT_EDIT_REQUEST';
export const SET_PROJECT_EDIT_SUCCESS = 'SET_PROJECT_EDIT_SUCCESS';
export const SET_PROJECT_EDIT_ERROR = 'SET_PROJECT_EDIT_ERROR'
