export const GET_ORG_REQUEST = 'GET_ORG_REQUEST';
export const GET_ORG_SUCCESS = 'GET_ORG_SUCCESS';
export const GET_ORG_ERROR = 'GET_ORG_ERROR';
export const SET_EMP_REQUEST = 'SET_EMP_REQUEST';
export const SET_EMP_SUCCESS = 'SET_EMP_SUCCESS';
export const SET_EMP_ERROR = 'SET_EMP_ERROR';